/* Contenido de la LP "Baker clon" (Máster MAIC) — copy real de go.founderz.com/maic-mql. */
window.BAKER = (function () {
  const u = (id, w = 900) => `https://images.unsplash.com/photo-${id}?w=${w}&q=72&auto=format&fit=crop`;
  return {
    photo: u,
    hero: {
      ratingPre: "4.8 en Trustpilot · 5.000+ reseñas",
      microsoft: "Certificado por Microsoft",
      title: "Domina la IA que está transformando el sector de los publicistas.",
      meta: "Máster Online · 3-4 meses",
      reelLabel: "30 segundos. Mira lo que vas a poder crear.",
      bulletsTitle: "Lo que vas a descubrir:",
      bullets: [
        "Temario completo: 6 módulos, de imagen a vídeo, audio y 3D",
        "Especialización para tu sector: publicidad, cine, moda, arquitectura, ilustración…",
        "Precios exactos, financiación al 0% y opciones Fundae",
        "Casos reales: qué crean los alumnos después del máster",
      ],
      formLabel: "Descubre el temario completo",
      formTitle: "Descarga el dossier",
      formSub: "Todo lo que necesitas para decidir, gratis y sin compromiso.",
      formNote: "Sin compromiso · Recíbelo al instante · Sin spam",
      cta: "Descargar dossier",
    },
    trust: { title: "Confían en nosotros", logos: ["BBVA", "EY", "Atlético de Madrid", "Mapfre", "Prosegur"] },
    quotes: {
      title: "¿Te suena?",
      items: [
        { text: "Llevo 20 años en esto. Y de repente, un júnior con Midjourney entrega en 2 horas lo que a mí me costaba una semana.", after: "3 meses después, lidera proyectos con IA en su estudio.", img: "1531123897727-8f129e1688ce" },
        { text: "Mis clientes ya piden piezas generadas con IA y yo sigo haciendo todo a mano. Me da miedo que elijan a alguien más rápido y más barato.", after: "3 meses después, integra IA en su proceso creativo y entrega el doble de proyectos.", img: "1544717305-2782549b5136" },
        { text: "Ya uso Midjourney y Runway a diario. Lo que encuentro online es siempre nivel principiante. Necesito profundidad real.", after: "3 meses después, workflows de producción profesional + el marco legal que nadie más enseña.", img: "1507003211169-0a1dd7228f2d" },
      ],
    },
    showcase: {
      label: "Creado por alumnos del master",
      title: "Empezaron exactamente donde estás tú. Mira lo que crean hoy.",
      cta: "Quiero aprender a crear así",
      items: [
        { title: "Mother Dough — Teaser surrealista", sub: "Creado por alumno con Runway + Midjourney", video: true, img: "1536440136628-849c177e76a1" },
        { title: "Desert Mystery — Cortometraje experimental", sub: "Creado por alumno con Sora + Kling", video: true, img: "1469474968028-56623f02e42e" },
        { title: "Leona 3D estilizada", sub: "Midjourney + Magnific", img: "1557800636-894a64c1696f" },
        { title: "Fotografía de producto", sub: "Perfume de lujo con IA", img: "1592945403244-b3fbafd7f539" },
        { title: "Render arquitectónico", sub: "Villa moderna con IA", img: "1600585154340-be6161a56a0c" },
      ],
    },
    program: {
      label: "El programa",
      title: "Imagen, vídeo, audio, motion, 3D. Con criterio profesional.",
      sub: "Aprende a usar las herramientas de IA que ya están transformando cada sector creativo. Sin base técnica necesaria.",
      stats: [
        { value: "9", label: "módulos" },
        { value: "+20", label: "profesores en activo" },
        { value: "5-15 min", label: "por clase" },
        { value: "Microsoft", label: "certificación incluida" },
      ],
      specTitle: "Elige tu especialización y aprende con casos de tu profesión",
      specs: [
        { name: "Ilustración", icon: "wand" }, { name: "Diseño Gráfico", icon: "sparkles" },
        { name: "Comunicación y RRSS", icon: "users" }, { name: "Cine y Audiovisual", icon: "play" },
        { name: "Moda", icon: "star" }, { name: "Fotografía", icon: "cpu" },
        { name: "Publicidad", icon: "globe" }, { name: "Arquitectura", icon: "briefcase" },
      ],
      includes: [
        "Certificación dual: Founderz + Microsoft",
        "12 meses de acceso y actualizaciones",
        "Masterclasses en directo con expertos",
        "Biblioteca de prompts creativos",
        "GPTs personalizados para imagen y vídeo",
        "Módulo legal especializado",
      ],
      learnTitle: "¿Qué aprenderás?",
      learn: ["Prompting avanzado", "Generación de imagen", "Generación de vídeo", "Edición de imagen", "Edición de vídeo", "Música con IA", "Voz sintética", "GPTs personalizados", "Workflows creativos", "Automatización", "Marca personal", "Portfolios", "Marco jurídico", "Avatares digitales"],
      toolsTitle: "Herramientas que dominarás",
      tools: ["Midjourney", "Adobe Firefly", "Runway", "Kling", "ElevenLabs", "HeyGen", "Recraft", "DaVinci Resolve", "Freepik AI", "Flora", "Weavy"],
    },
    syllabus: {
      title: "Temario completo",
      modules: [
        { n: "1", title: "Transformación del proceso creativo", lessons: ["Método y criterio profesional para trabajar con IA", "Pensar antes de producir: la IA como colaborador estratégico", "Errores más comunes al integrar IA en el proceso creativo", "Casos reales de transformación en estudios y agencias"], teachers: ["Fabiana Aguilar", "Anna Cejudo"] },
        { n: "2", title: "Preproducción y control creativo", lessons: ["Prompting diferenciado para texto, imagen y vídeo", "Creación de asistentes y GPTs personalizados", "Criterio visual antes de generar: moodboards y referencias con IA", "Comunicación profesional con modelos generativos"], teachers: ["Paco Chavinet", "Javier de la Chica"] },
        { n: "3", title: "Producción y postproducción de imagen con IA", lessons: ["Generación de imágenes profesionales con las mejores herramientas", "Técnicas avanzadas de edición: inpainting, outpainting, upscaling", "Optimización de flujo de trabajo y créditos", "Vectorización y preparación para uso comercial"], teachers: ["Jaime Sanjuan", "Joss López", "Koldo Huici"] },
        { n: "4", title: "Producción y postproducción de vídeo con IA", tag: "Nuevo", lessons: ["Generación de vídeos profesionales con herramientas punteras", "Organización de proyectos creativos complejos", "Edición avanzada y postproducción con IA", "Técnicas de mejora y transformación de vídeo"], teachers: ["Hilario Abad", "Nekodificador", "Eduard Puig"] },
        { n: "5", title: "Diseño de voz, sonido y música con IA", tag: "Nuevo", lessons: ["Generación de voces profesionales y clonación de voz", "Creación de bandas sonoras y música original con IA", "Acabado sonoro profesional para proyectos creativos", "Herramientas de audio: ElevenLabs, Suno y más"], teachers: ["Alby Ojeda"] },
        { n: "6", title: "Construcción de flujos de trabajo creativos", tag: "Nuevo", lessons: ["De herramientas sueltas a sistemas de producción escalables", "Diseño de workflows visuales con IA", "Automatización de procesos repetitivos", "Creación de herramientas creativas propias sin programar"], teachers: ["Alex Caracuel", "Ramón Iborra"] },
      ],
      lockedTitle: "3 módulos más te esperan",
      lockedSub: "Descarga el dossier para ver el temario completo.",
      lockedCta: "Desbloquear temario completo",
      lockedNote: "Sin coste · Acceso inmediato",
    },
    method: {
      label: "Así se aprende",
      title: "Clases cortas. Herramientas reales. Resultados inmediatos.",
      videoTitle: "Generación de vídeo con IA",
      videoSub: "Tutorial paso a paso",
      intro: "Nada de vídeos de una hora que abandonas a los 10 minutos. Aquí cada clase dura 5-15 minutos, va directa al grano y te deja con algo que puedes aplicar hoy.",
      items: [
        { icon: "clock", title: "Microclases de 5-15 min", text: "Un concepto, una herramienta, un resultado. Sin relleno. Diseñadas para que aprendas en ratos sueltos, no en maratones." },
        { icon: "rocket", title: "Contenido que no caduca en 2 semanas", text: "Las herramientas de IA cambian cada semana. El temario se actualiza constantemente para que lo que aprendes hoy siga siendo útil mañana." },
        { icon: "calendar", title: "Masterclasses quincenales en directo", text: "Sesiones live con profesionales que están aplicando IA en agencias, productoras y estudios reales. Preguntas en directo, casos del momento." },
        { icon: "users", title: "+20 profesores en activo, no teóricos", text: "Directores de arte, cineastas, diseñadores, juristas. Gente que usa IA todos los días en proyectos reales — no académicos que leen papers." },
        { icon: "globe", title: "100% online, a tu ritmo", text: "Sin horarios fijos. Desde cualquier sitio. 1-2 horas al día cuando tú quieras. Compatible con tu trabajo." },
      ],
    },
    testimonials: {
      ratingPre: "4.8 en Trustpilot",
      title: "Más de 5.000 alumnos verificados ya lo dicen.",
      featured: { text: "La parte del máster que más me ha gustado es la de aplicaciones al mundo del marketing y ventas, donde he podido ver un potencial de optimizar procesos, hacer presentaciones, editar productos o hacer campañas de cualquier tipo.", name: "Fredy Civit", role: "Head of eCommerce de Nestlé Spain", img: "1507003211169-0a1dd7228f2d" },
      items: [
        { text: "Me apasiona la fotografía y el diseño y al entrar en este mundo de la IA, observo los increíbles resultados que se pueden lograr luego de aprender a usarla adecuadamente.", name: "Fiorella Ortegon", role: "Reseña verificada en Trustpilot", avatar: "https://i.pravatar.cc/96?img=31" },
        { text: "Me parece un contenido muy ameno y fácil de consumir, en cuanto al formato de vídeos cortos e información de calidad transmitida.", name: "Slow — Visual Narratives", role: "Reseña verificada en Trustpilot", avatar: "https://i.pravatar.cc/96?img=14" },
        { text: "Soy director de arte con 15 años de experiencia. Tenía miedo de que la IA me dejase obsoleto. Ahora es mi herramienta más potente.", name: "Juan Hernández", role: "Reseña verificada en Trustpilot", avatar: "https://i.pravatar.cc/96?img=68" },
      ],
    },
    teachers: {
      label: "Equipo docente",
      title: "Quién te va a enseñar",
      sub: "Profesionales en activo aplicando IA en estudios, agencias y productoras. Más expertos de Microsoft que llevan años en el frente.",
      cta: "Quiero aprender con ellos",
      items: [
        { name: "Fabiana Aguilar", role: "Directora del programa", company: "Founderz", img: 47 },
        { name: "Hilario Abad", role: "Cineasta especializado en IA", company: "Hilario Abad", img: 12 },
        { name: "Nekodificador", role: "Creativo audiovisual y Creador de Contenido", company: "", img: 33 },
        { name: "Magda Teruel", role: "Copilot Partner Solutions Architect", company: "Microsoft", img: 45 },
        { name: "Javier de la Chica", role: "Director Creativo", company: "Contanimation", img: 51 },
        { name: "Anna Cejudo", role: "Cofundadora & Co-CEO", company: "Founderz", img: 26 },
        { name: "Jaime Sanjuan", role: "Director de Arte Digital e Instructor", company: "", img: 60 },
        { name: "Paco Chavinet", role: "Artista visual y Director Creativo", company: "Milkshakes", img: 13 },
        { name: "Alex Caracuel", role: "Project Manager | Creative AI & Media", company: "Wimeik AI Studio", img: 15 },
        { name: "Pau Garcia-Milà", role: "Cofundador & Co-CEO", company: "Founderz", img: 8 },
        { name: "Ramón Iborra", role: "CEO", company: "Artilabs", img: 52 },
        { name: "María Montes", role: "Jurista tecnológica", company: "", img: 24 },
      ],
    },
    awards: { label: "Reconocimientos", logos: ["Forbes", "ASU+GSV", "GESAwards", "EdTech Digest", "EdTech", "Excellence", "Global Innovation"] },
    faqs: {
      title: "Todo lo que necesitas saber.",
      items: [
        { q: "¿Cuánto cuesta el Máster?", a: "Descarga el dossier gratuito y recibirás los precios exactos, las opciones de financiación al 0% y las ayudas Fundae disponibles." },
        { q: "¿Necesito saber programar?", a: "No. El máster está diseñado para perfiles creativos sin base técnica: partimos de cero y avanzamos paso a paso." },
        { q: "¿Qué certificación recibiré?", a: "Una certificación dual Founderz + Microsoft al completar el programa." },
        { q: "¿Cuánto tiempo necesito al día?", a: "Con 1-2 horas al día es suficiente. Las clases duran 5-15 minutos y el ritmo lo marcas tú." },
        { q: "¿Y si no me convence?", a: "Tienes una garantía de 15 días sin preguntas: si no es para ti, te devolvemos el importe." },
        { q: "¿Qué herramientas aprendo?", a: "Midjourney, Adobe Firefly, Runway, Kling, ElevenLabs, HeyGen, Recraft, DaVinci Resolve, Freepik AI y más." },
      ],
    },
    finalCta: {
      label: "Sin compromiso",
      title: "Descubre el programa completo y habla con un asesor hoy.",
      sub: "Temario completo, las 7 especializaciones, metodología, precios y casos reales de alumnos creativos.",
      checks: ["Sin presión: te informamos, decides tú", "Certificación Founderz + Microsoft incluida", "Garantía de 15 días sin preguntas"],
      formTitle: "Descarga el dossier gratuito",
      formSub: "Rellena el formulario y recíbelo al instante.",
      cta: "Descargar dossier",
      note: "Sin compromiso · Recíbelo al instante · Sin spam",
    },
  };
})();
